# Generated by Django 3.2.7 on 2024-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='closed_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customerservice',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ticketreply',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketsubject',
            name='type',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerService',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Ticketreply',
        ),
        migrations.DeleteModel(
            name='TicketSubject',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
